
"use client";

import * as React from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import type { Student } from "@/lib/definitions";
import { Button } from "@/components/ui/button";
import { Form } from "@/components/ui/form";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { StudentFormFields, studentFormSchema, type StudentFormData } from "./student-form-fields";
import { Save, XCircle } from "lucide-react";

interface AddStudentFormProps {
  onSave: (student: Omit<Student, 'id'>) => Promise<void>; // ID will be generated by saveStudent
  onCancel: () => void;
}

export function AddStudentForm({ onSave, onCancel }: AddStudentFormProps) {
  const form = useForm<StudentFormData>({
    resolver: zodResolver(studentFormSchema),
    defaultValues: {
      rut: "",
      firstName: "",
      lastNamePaternal: "",
      lastNameMaternal: "",
      email: "",
      career: "",
      commune: "",
      tutor: "",
      practicumLevel: "",
      specialConditions: "",
    },
  });

  const onSubmit = async (data: StudentFormData) => {
    // ID is not part of the form data for adding, it's generated or assigned by the backend/data layer
    const newStudentData: Omit<Student, 'id'> = {
      rut: data.rut,
      firstName: data.firstName,
      lastNamePaternal: data.lastNamePaternal,
      lastNameMaternal: data.lastNameMaternal,
      email: data.email,
      career: data.career,
      commune: data.commune,
      tutor: data.tutor,
      practicumLevel: data.practicumLevel,
      specialConditions: data.specialConditions,
    };
    await onSave(newStudentData);
    form.reset(); 
  };

  return (
    <Card className="shadow-lg">
      <CardHeader>
        <CardTitle>Agregar nuevo estudiante a la base de datos</CardTitle>
        <CardDescription>(Los campos con * son obligatorios)</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <StudentFormFields form={form} />
            <div className="flex justify-start gap-4 pt-4">
              <Button type="submit" className="bg-green-500 hover:bg-green-600 text-white" disabled={form.formState.isSubmitting}>
                <Save className="mr-2 h-4 w-4" /> Guardar estudiante
              </Button>
              <Button type="button" variant="outline" onClick={onCancel}>
                <XCircle className="mr-2 h-4 w-4" /> Cancelar
              </Button>
            </div>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
}
